"""S-1103 — detection false-positive / recall baseline.

Drives a labelled corpus through the REAL engine Gate-3 classifier
(SaroEngine._gate3_risk_classification, keyword-only) and measures per-domain
precision and recall one-vs-rest. Writes docs/metrics/detection-baseline.md and
compares against the committed baseline; CI fails if any domain's precision
regresses by more than 5 percentage points.

The corpus is intentionally adversarial: positives include paraphrases with no
literal keyword (recall misses are real), and hard negatives are benign sentences
with broad-keyword overlaps (false positives are real). The numbers are meant to
be honest, not flattering.
"""
from __future__ import annotations

import json
from pathlib import Path

import pytest

from engine import MIT_DOMAINS, SARoEngine
from schemas import BatchIn, SampleIn

pytestmark = [pytest.mark.regression, pytest.mark.integration]

ROOT = Path(__file__).resolve().parent.parent
FIX = ROOT / "tests" / "fixtures" / "fp_baseline"
CORPUS = FIX / "corpus.json"
BASELINE = FIX / "baseline.json"
REPORT_MD = ROOT / "docs" / "metrics" / "detection-baseline.md"

PRECISION_REGRESSION_TOLERANCE = 0.05  # 5 percentage points


def _classify(samples: list[SampleIn]) -> dict[str, set[str]]:
    """Run samples through the real keyword-only Gate-3 classifier.

    Returns sample_id -> set(flagged domains). Built with __new__ so no DB is
    needed: the classifier only reads _RISK_SIGNALS and self._sample_findings.
    """
    eng = SARoEngine.__new__(SARoEngine)
    eng._sample_findings = []
    batch = BatchIn(samples=samples)
    flags, _ = eng._gate3_risk_classification(batch)
    out: dict[str, set[str]] = {s.sample_id: set() for s in samples}
    for f in flags:
        out.setdefault(f.sample_id, set()).add(f.domain)
    return out


def _load_corpus() -> tuple[list[SampleIn], dict[str, str]]:
    """Return (samples, sample_id -> positive-domain-or-'__neg__')."""
    data = json.loads(CORPUS.read_text(encoding="utf-8"))
    samples: list[SampleIn] = []
    label: dict[str, str] = {}
    idx = 0

    def _add(text: str, pos_domain: str) -> None:
        nonlocal idx
        sid = f"s{idx}"
        idx += 1
        samples.append(SampleIn(sample_id=sid, text=text))
        label[sid] = pos_domain

    for text in data["benign_pool"]:
        _add(text, "__neg__")
    for domain, sets in data["domains"].items():
        for text in sets.get("positives", []):
            _add(text, domain)
        for text in sets.get("hard_negatives", []):
            _add(text, "__neg__")
    return samples, label


def _measure() -> dict[str, dict]:
    samples, label = _load_corpus()
    flagged = _classify(samples)

    metrics: dict[str, dict] = {}
    for d in MIT_DOMAINS:
        tp = fp = fn = tn = 0
        for s in samples:
            is_pos = label[s.sample_id] == d           # ground truth: this sample exhibits d
            pred = d in flagged.get(s.sample_id, set())  # engine flagged d
            if is_pos and pred:
                tp += 1
            elif is_pos and not pred:
                fn += 1
            elif not is_pos and pred:
                fp += 1
            else:
                tn += 1
        decisions = tp + fp + fn + tn
        precision = tp / (tp + fp) if (tp + fp) else None
        recall = tp / (tp + fn) if (tp + fn) else None
        metrics[d] = {
            "tp": tp, "fp": fp, "fn": fn, "tn": tn,
            "labelled_decisions": decisions,
            "precision": round(precision, 4) if precision is not None else None,
            "recall": round(recall, 4) if recall is not None else None,
        }
    return metrics


def _write_report(metrics: dict[str, dict]) -> None:
    REPORT_MD.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# SARO Detection Baseline — Precision & Recall",
        "",
        "> Generated by `tests/test_fp_baseline.py` (S-1103). Keyword-only Gate-3 classifier,",
        "> measured one-vs-rest over `tests/fixtures/fp_baseline/corpus.json`. Honest numbers:",
        "> paraphrased positives surface recall misses; hard negatives surface false positives.",
        "",
        "| MIT domain | Precision | Recall | TP | FP | FN | TN | Labelled decisions |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for d in MIT_DOMAINS:
        m = metrics[d]
        p = "n/a" if m["precision"] is None else f"{m['precision']:.2f}"
        r = "n/a" if m["recall"] is None else f"{m['recall']:.2f}"
        lines.append(
            f"| {d} | {p} | {r} | {m['tp']} | {m['fp']} | {m['fn']} | {m['tn']} | {m['labelled_decisions']} |"
        )
    lines += [
        "",
        "**Interpretation.** Low precision in a domain means broad keywords (e.g. *fail*, *error*,",
        "*private*, *attack*) over-trigger on benign text — candidates for regex tightening. Low",
        "recall means the keyword set misses paraphrased risks — candidates for signal expansion.",
        "CI fails if any domain's precision drops more than 5 percentage points below the committed",
        "baseline (`tests/fixtures/fp_baseline/baseline.json`).",
        "",
    ]
    REPORT_MD.write_text("\n".join(lines), encoding="utf-8")


def test_baseline_corpus_has_100plus_decisions_per_domain():
    metrics = _measure()
    for d in MIT_DOMAINS:
        assert metrics[d]["labelled_decisions"] >= 100, (
            f"{d}: only {metrics[d]['labelled_decisions']} labelled decisions (<100)"
        )


def test_detection_precision_no_regression(monkeypatch):
    # Force keyword-only: never call the optional LLM judge during measurement.
    monkeypatch.delenv("ANTHROPIC_API_KEY", raising=False)

    metrics = _measure()
    _write_report(metrics)

    if not BASELINE.exists():
        # Seed run: establish the baseline, then pass.
        BASELINE.write_text(json.dumps(metrics, indent=2), encoding="utf-8")
        pytest.skip("baseline.json seeded — re-run to enforce regression gate")

    baseline = json.loads(BASELINE.read_text(encoding="utf-8"))
    regressions = []
    for d in MIT_DOMAINS:
        base_p = baseline.get(d, {}).get("precision")
        cur_p = metrics[d]["precision"]
        if base_p is None or cur_p is None:
            continue
        if cur_p < base_p - PRECISION_REGRESSION_TOLERANCE:
            regressions.append(f"{d}: precision {cur_p:.2f} < baseline {base_p:.2f} - 0.05")

    assert not regressions, "Detection precision regressed:\n  " + "\n  ".join(regressions)
