"""
DPA in-app delivery service (SAR-009 / SPEC-G3).

Generates a GDPR Article 28 DPA PDF for a given tenant using
WeasyPrint + Jinja2 template injection.
"""
from __future__ import annotations

import logging
from datetime import date
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

_TEMPLATE_PATH = Path(__file__).parent.parent / "docs" / "legal" / "saro-dpa-template-v1.0.md"
_DPA_VERSION = "1.0"


def _render_dpa_markdown(tenant_name: str, execution_date: Optional[str] = None) -> str:
    """Render the DPA markdown with tenant name and date substituted."""
    if not _TEMPLATE_PATH.exists():
        raise FileNotFoundError(f"DPA template not found at {_TEMPLATE_PATH}")

    template_content = _TEMPLATE_PATH.read_text(encoding="utf-8")
    today = execution_date or date.today().isoformat()

    # Inject tenant-specific values (both {{}} and Jinja2-style)
    rendered = template_content.replace("{{TENANT_NAME}}", tenant_name)
    rendered = rendered.replace("{{EXECUTION_DATE}}", today)
    rendered = rendered.replace("{{DPA_VERSION}}", _DPA_VERSION)
    # Also inject the tenant name into the [CUSTOMER LEGAL ENTITY NAME] bracket placeholder
    rendered = rendered.replace("[CUSTOMER LEGAL ENTITY NAME]", tenant_name)
    rendered = rendered.replace("[EXECUTION_DATE]", today)

    # Try Jinja2 rendering as well (no-op if not installed or no Jinja2 vars present)
    try:
        from jinja2 import Template
        rendered = Template(rendered).render(
            tenant_name=tenant_name,
            execution_date=today,
            dpa_version=_DPA_VERSION,
        )
    except Exception:
        pass  # Plain string replace already done above

    return rendered


def generate_dpa_pdf(tenant_name: str, tenant_slug: str) -> bytes:
    """
    Generate a DPA PDF for the given tenant.
    Returns the PDF as bytes.
    """
    markdown_content = _render_dpa_markdown(tenant_name)

    # Convert markdown -> HTML -> PDF via WeasyPrint
    try:
        import markdown as md_lib
        html_body = md_lib.markdown(markdown_content, extensions=["tables", "fenced_code"])
    except ImportError:
        # Fallback: wrap in pre tags
        html_body = f"<pre>{markdown_content}</pre>"

    html = f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body {{ font-family: Arial, sans-serif; font-size: 11pt; margin: 40px; color: #222; }}
  h1 {{ font-size: 18pt; color: #1a1a2e; border-bottom: 2px solid #1a1a2e; padding-bottom: 8px; }}
  h2 {{ font-size: 14pt; color: #1a1a2e; margin-top: 24px; }}
  h3 {{ font-size: 12pt; color: #333; }}
  table {{ border-collapse: collapse; width: 100%; margin: 16px 0; }}
  th, td {{ border: 1px solid #ccc; padding: 6px 10px; text-align: left; }}
  th {{ background: #f0f4f8; font-weight: bold; }}
  .disclaimer {{ background: #fff3cd; border: 1px solid #ffc107; padding: 12px; border-radius: 4px; margin: 16px 0; }}
  .footer {{ font-size: 9pt; color: #666; text-align: center; margin-top: 40px; border-top: 1px solid #ccc; padding-top: 8px; }}
</style>
</head>
<body>
<div class="disclaimer">
<strong>SARO DPA v{_DPA_VERSION} — {tenant_name}</strong><br>
This Data Processing Agreement is provided as audit evidence. It does not constitute legal advice.
Human review and sign-off by qualified legal personnel is required before execution.
</div>
{html_body}
<div class="footer">
Generated by SARO v8.0.0 · GDPR Article 28 Data Processing Agreement · Version {_DPA_VERSION}
</div>
</body>
</html>"""

    try:
        from weasyprint import HTML
        pdf_bytes = HTML(string=html).write_pdf()
        return pdf_bytes
    except ImportError:
        logger.warning("WeasyPrint not installed — returning HTML as fallback")
        return html.encode("utf-8")
    except Exception as exc:
        logger.error("WeasyPrint PDF generation failed: %s", exc)
        raise
