"""Persist observation findings into the evidence tables the UI reads.

The observation adapters (Vertex/Azure, STORY-359/360) parse provider logs into
body-free ``NormalizedInvocationRecord``s and the observation rule packs evaluate
them into ``Finding`` objects — but until now those findings terminated at a
print statement / JSON file (``scripts/demo_azure_vertex_e2e.py``). No persona
could see or act on them, because every persona-facing page (TRACE View, Risk
Register, Compliance Hub) reads the content-scoring evidence tables
(``audits`` / ``scan_reports`` / ``audit_traces``), and nothing wrote there.

This service is that missing writer. It maps observation ``Finding``s onto the
same evidence tables — hash-chained, tenant-bound — so the three personas review
and act on Vertex/Azure findings in the existing UI.

**Honesty guarantees (compliance-guard, INV-2, positioning):**

* Traces are written with ``check_type = "observation"`` — visibly distinct from
  the content-scoring ``"risk_domain"`` / ``"gate_result"`` rows. An observation
  finding is *evidence about log coverage/scope*, never a content-risk verdict.
* ``ScanReport.report_json["score_basis"] == "observation_coverage"`` and a
  disclaimer string are stored, so the score on the dashboards is labeled for
  what it is (a severity rollup of observation findings), not a content score.
* The observation records are body-free by construction; nothing here can write
  message content, because the ``Finding``/record schema has no field for it.
* Tenancy comes from the caller's operator config, never from the log (INV-3).
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from typing import Optional

from sqlalchemy.orm import Session

from adapters.contract import NormalizedInvocationRecord
from models import Audit, AuditTrace, ScanReport
from rule_packs.observation.evaluate import Finding, evaluate_records
from rule_packs.observation.loader import ObservationPack
from services.hash_chain_service import LEGACY_SENTINEL, compute_event_hash

# Severity → (risk weight, trace result). Weight feeds the ScanReport rollup;
# result is one of the non-pass values the UI's TRACE/Remedy/Dashboard filters
# key on ({fail, warn, flagged, triggered}) so findings are actionable.
_SEVERITY = {
    "CRITICAL": (1.0, "flagged"),
    "HIGH": (1.0, "flagged"),
    "MEDIUM": (0.6, "warn"),
    "LOW": (0.3, "warn"),
    "INFO": (0.05, "warn"),
}
# Unknown severity fails SAFE (most-severe) in an evidence system — a custom
# pack emitting an unmapped severity must never be silently downgraded.
_DEFAULT_WEIGHT, _DEFAULT_RESULT = 1.0, "flagged"

SCORE_BASIS = "observation_coverage"
DISCLAIMER = (
    "Observation-coverage evidence generated by SARO from provider invocation "
    "logs (body-free, INV-2). The score is a severity rollup of observation "
    "findings — log completeness, tool-scope, and provider errors — not a "
    "content-risk verdict. Human review required; SARO does not certify."
)


@dataclass
class ObservationIngestResult:
    audit_id: Optional[uuid.UUID] = None
    system_id: str = ""
    records_evaluated: int = 0
    findings_persisted: int = 0
    overall_score: float = 0.0
    findings_by_rule: dict[str, int] = field(default_factory=dict)
    skipped_duplicate: bool = False


def _rollup_score(findings: list[Finding]) -> float:
    """Worst-observation severity weight across the batch, 0 if clean."""
    if not findings:
        return 0.0
    return max(
        _SEVERITY.get(f.severity, (_DEFAULT_WEIGHT, _DEFAULT_RESULT))[0]
        for f in findings
    )


def persist_observation_findings(
    db: Session,
    *,
    tenant_id: uuid.UUID,
    system_id: str,
    records: list[NormalizedInvocationRecord],
    packs: list[ObservationPack],
    user_id: Optional[uuid.UUID] = None,
    batch_id: Optional[str] = None,
) -> ObservationIngestResult:
    """Evaluate ``records`` against ``packs`` and persist the findings as evidence.

    Writes one ``Audit`` (parent), one ``ScanReport`` (labeled observation-basis),
    and one ``AuditTrace`` per finding (hash-chained). A record with no findings
    still yields a ``pass`` trace so the invocation is visible in TRACE View.

    Idempotent on ``batch_id``: if an Audit already carries it, returns early with
    ``skipped_duplicate=True`` — re-running an ingest never double-writes.
    """
    batch_id = batch_id or f"obs:{system_id}"
    # INV-3: scope the idempotency lookup to THIS tenant. batch_id has no unique
    # constraint and system_id is operator free text, so two tenants can share
    # "obs:gemini-prod" — an unscoped match would hand tenant B tenant A's audit
    # and silently drop B's findings.
    existing = (
        db.query(Audit)
        .filter(Audit.batch_id == batch_id, Audit.tenant_id == tenant_id)
        .first()
    )
    if existing is not None:
        return ObservationIngestResult(
            audit_id=existing.id, system_id=system_id, skipped_duplicate=True
        )

    findings = evaluate_records(records, packs)
    score = _rollup_score(findings)
    now = datetime.now(tz=timezone.utc)

    by_rule: dict[str, int] = {}
    for f in findings:
        by_rule[f.rule_id] = by_rule.get(f.rule_id, 0) + 1

    audit = Audit(
        tenant_id=tenant_id,
        user_id=user_id,
        batch_id=batch_id,
        dataset_name=f"Vertex observation — {system_id}",
        sample_count=len(records),
        status="completed",
        completed_at=now,
    )
    db.add(audit)
    db.flush()  # assign audit.id for the FKs below

    db.add(
        ScanReport(
            audit_id=audit.id,
            tenant_id=tenant_id,
            overall_risk_score=score,
            confidence_score=1.0,  # deterministic parse — no sampling uncertainty
            report_json={
                "score_basis": SCORE_BASIS,
                "disclaimer": DISCLAIMER,
                "system_id": system_id,
                "records_evaluated": len(records),
                "findings_total": len(findings),
                "findings_by_rule": by_rule,
                "packs": [{"ref": p.pack_ref, "hash": p.content_hash} for p in packs],
            },
            rule_pack_hash=(packs[0].content_hash if packs else None),
        )
    )

    _persist_observation_traces(db, audit.id, tenant_id, findings, now)

    db.commit()
    return ObservationIngestResult(
        audit_id=audit.id,
        system_id=system_id,
        records_evaluated=len(records),
        findings_persisted=len(findings),
        overall_score=score,
        findings_by_rule=by_rule,
    )


def _persist_observation_traces(
    db: Session,
    audit_id: uuid.UUID,
    tenant_id: uuid.UUID,
    findings: list[Finding],
    created_at: datetime,
) -> None:
    """One hash-chained AuditTrace per finding (or a single pass trace if clean).

    Mirrors routers/scan.py::_persist_traces chaining semantics, reusing
    services/hash_chain_service so an observation trace verifies on the same
    ``GET /api/v1/audit/verify-chain`` path as a content-scoring trace.
    """
    last = (
        db.query(AuditTrace.event_hash)
        .filter(
            AuditTrace.audit_id == audit_id,
            AuditTrace.event_hash.isnot(None),
            AuditTrace.event_hash != LEGACY_SENTINEL,
        )
        .order_by(AuditTrace.created_at.desc())
        .first()
    )
    prev_hash: Optional[str] = last[0] if last else None

    rows: list[dict] = []
    if findings:
        for f in findings:
            _weight, result = _SEVERITY.get(
                f.severity, (_DEFAULT_WEIGHT, _DEFAULT_RESULT)
            )
            rows.append(
                {
                    "gate_name": "Observation",
                    "check_type": "observation",
                    "check_name": f"{f.rule_id}: {f.title}",
                    "result": result,
                    "reason": f.title,
                    "remediation_hint": f.remediation,
                    "signal_text": f"request {f.request_id}"[:500],
                    "detail_json": {
                        "rule_id": f.rule_id,
                        "severity": f.severity,
                        "pack_ref": f.pack_ref,
                        "pack_hash": f.pack_hash,
                        "request_id": f.request_id,
                        **f.detail,
                    },
                }
            )
    else:
        rows.append(
            {
                "gate_name": "Observation",
                "check_type": "observation",
                "check_name": "OBS-CLEAN: no observation findings",
                "result": "pass",
                "reason": "All evaluated invocations were observation-complete.",
                "remediation_hint": None,
                "signal_text": None,
                "detail_json": None,
            }
        )

    for i, row in enumerate(rows):
        # Strictly increasing created_at so chain order is deterministic even
        # when many findings land in the same batch, and so the value hashed
        # equals the value stored (verify recomputes from the stored column).
        row_ts = created_at + timedelta(microseconds=i)
        event_data = {
            "id": uuid.uuid4(),
            "audit_id": audit_id,
            "gate_id": None,
            "gate_name": row["gate_name"],
            "check_type": row["check_type"],
            "check_name": row["check_name"],
            "result": row["result"],
            "reason": row["reason"],
            "signal_text": row["signal_text"],
            "remediation_hint": row["remediation_hint"],
            "created_at": row_ts.isoformat(),
        }
        event_hash = compute_event_hash(event_data, prev_hash)
        db.add(
            AuditTrace(
                id=event_data["id"],
                audit_id=audit_id,
                tenant_id=tenant_id,
                gate_id=None,
                gate_name=row["gate_name"],
                check_type=row["check_type"],
                check_name=row["check_name"],
                result=row["result"],
                reason=row["reason"],
                detail_json=row["detail_json"],
                remediation_hint=row["remediation_hint"],
                signal_text=row["signal_text"],
                created_at=row_ts,
                event_hash=event_hash,
                prev_hash=prev_hash,
            )
        )
        prev_hash = event_hash
