"""CF-05: Governance Trust Page tab."""
from __future__ import annotations

import requests
import streamlit as st


def render(token: str) -> None:
    api_base = st.session_state.get("api_base", "http://localhost:8000")
    st.header("🏛️ Governance Trust Documents")
    st.caption(
        "Download SARO's NIST AI RMF self-assessment and EU AI Act position statement. "
        "These are audit evidence documents — they do not constitute regulatory certification."
    )

    try:
        meta_resp = requests.get(
            f"{api_base}/api/v1/governance/meta",
            headers={"Authorization": f"Bearer {token}"},
            timeout=10,
        )
        meta = meta_resp.json() if meta_resp.status_code == 200 else {}
    except Exception:
        meta = {}

    col1, col2 = st.columns(2)

    with col1:
        nist_meta = meta.get("nist_self_assessment", {})
        st.subheader("NIST AI RMF 1.0 Self-Assessment")
        if nist_meta:
            st.caption(
                f"Version {nist_meta.get('version', 'N/A')} · "
                f"Reviewed {nist_meta.get('reviewed_at', 'N/A')} by {nist_meta.get('reviewer', 'N/A')}"
            )
        if st.button("Download NIST PDF", type="primary", key="gov_nist_dl"):
            try:
                r = requests.get(
                    f"{api_base}/api/v1/governance/docs/nist-self-assessment",
                    headers={"Authorization": f"Bearer {token}"},
                    timeout=20,
                )
                if r.status_code == 200:
                    st.download_button(
                        "Save NIST PDF",
                        data=r.content,
                        file_name="saro-nist-ai-rmf-self-assessment-v1.0.pdf",
                        mime="application/pdf",
                    )
                else:
                    st.error(f"Download failed ({r.status_code})")
            except Exception as e:
                st.error(str(e))

    with col2:
        eu_meta = meta.get("eu_ai_act_position", {})
        st.subheader("EU AI Act Position Statement")
        if eu_meta:
            st.caption(
                f"Version {eu_meta.get('version', 'N/A')} · "
                f"Reviewed {eu_meta.get('reviewed_at', 'N/A')} by {eu_meta.get('reviewer', 'N/A')}"
            )
        if st.button("Download EU AI Act PDF", type="primary", key="gov_eu_dl"):
            try:
                r = requests.get(
                    f"{api_base}/api/v1/governance/docs/eu-ai-act-position",
                    headers={"Authorization": f"Bearer {token}"},
                    timeout=20,
                )
                if r.status_code == 200:
                    st.download_button(
                        "Save EU AI Act PDF",
                        data=r.content,
                        file_name="saro-eu-ai-act-position-v1.0.pdf",
                        mime="application/pdf",
                    )
                else:
                    st.error(f"Download failed ({r.status_code})")
            except Exception as e:
                st.error(str(e))

    st.divider()
    st.caption(
        "**Disclaimer:** These documents are audit evidence generated by SARO v8.0.0. "
        "They do not constitute regulatory certification, legal advice, or compliance approval. "
        "Human review and sign-off by qualified personnel is required before any regulatory submission."
    )
