#!/usr/bin/env python3
"""Azure OpenAI + Vertex AI end-to-end observation demo runner.

Walks SARO's observation pipeline live, per provider, in five staged steps:

    [1/5] read the customer-owned log export        (read-only, INV-6)
    [2/5] adapter parse -> NormalizedInvocationRecord
    [3/5] contract invariants (body-free, availability honesty)
    [4/5] observation rule-pack evaluation -> findings
    [5/5] evidence summary (+ optional JSON artifact)

Everything runs offline against the committed deterministic corpora
(`tests/fixtures/azure/corpus.ndjson`, `tests/fixtures/vertex/corpus.ndjson`) —
the same bytes CI verifies. Zero network, zero cloud credentials, zero model
calls (INV-1), zero writes outside the optional ``--json-out`` path. The output
is deterministic so the committed screencast (docs/demo/) reproduces exactly.

Cloud-side setup for a *real* export (Azure Diagnostic Settings, GCP audit-log
sink) is documented in docs/demo/AZURE_VERTEX_E2E_DEMO.md — that part happens
in the customer's cloud account, never inside SARO.

Usage:
    python scripts/demo_azure_vertex_e2e.py                 # both providers
    python scripts/demo_azure_vertex_e2e.py --provider azure
    python scripts/demo_azure_vertex_e2e.py --json-out artifacts/demo.json
    python scripts/demo_azure_vertex_e2e.py --pace 0.6      # paced, for capture
"""

from __future__ import annotations

import argparse
import json
import sys
import time
import uuid
from collections.abc import Callable
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

_REPO_ROOT = Path(__file__).resolve().parent.parent
if str(_REPO_ROOT) not in sys.path:  # script is runnable from any cwd
    sys.path.insert(0, str(_REPO_ROOT))

from adapters.azure_openai.parse import parse_record as azure_parse  # noqa: E402
from adapters.azure_openai.records import AzureAdapterConfig  # noqa: E402
from adapters.contract import NormalizedInvocationRecord  # noqa: E402
from adapters.export_source import ExportRecordError, RecordSkipped  # noqa: E402
from adapters.vertex_ai.parse import parse_record as vertex_parse  # noqa: E402
from adapters.vertex_ai.records import VertexAdapterConfig  # noqa: E402
from rule_packs.observation.evaluate import Finding, evaluate_records  # noqa: E402
from rule_packs.observation.loader import (  # noqa: E402
    ObservationPack,
    load_genesis_packs,
)

from _version import __version__ as SARO_VERSION  # noqa: E402

# Operator-supplied demo tenant binding (INV-3: tenancy is never read from logs).
DEMO_TENANT_ID = uuid.UUID("00000000-0000-4000-8000-000000000d50")

# Tenant tool policy for the demo — matches the corpora's enriched records so
# the tool-scope rules have real violations to surface.
DEMO_ALLOWED_TOOLS = {
    "azure": ("search_care_guidelines",),
    "vertex": ("lookup_care_pathway",),
}

# Required disclaimer, verbatim per docs/COMPLIANCE_CLAIMS_MATRIX.md.
DISCLAIMER = (
    f"This report is audit evidence generated by SARO v{SARO_VERSION}. It does "
    "not constitute regulatory certification, legal advice, or compliance "
    "approval. Human review and sign-off by qualified personnel is required "
    "before any regulatory submission."
)


@dataclass(frozen=True)
class ProviderSpec:
    key: str
    display: str
    adapter_id: str
    corpus: Path
    source_label: str
    config: Any
    parse: Callable[..., NormalizedInvocationRecord]


def _provider_specs(
    azure_corpus: Path | None, vertex_corpus: Path | None
) -> dict[str, ProviderSpec]:
    return {
        "azure": ProviderSpec(
            key="azure",
            display="Azure OpenAI",
            adapter_id="azure-openai-diagnostic-log",
            corpus=azure_corpus or _REPO_ROOT / "tests/fixtures/azure/corpus.ndjson",
            source_label="Azure Diagnostic Settings export (category=RequestResponse)",
            config=AzureAdapterConfig(
                tenant_id=DEMO_TENANT_ID,
                container="insights-logs-requestresponse",
                prefix="demo-tenant/",
            ),
            parse=azure_parse,
        ),
        "vertex": ProviderSpec(
            key="vertex",
            display="Vertex AI",
            adapter_id="vertex-ai-audit-log",
            corpus=vertex_corpus or _REPO_ROOT / "tests/fixtures/vertex/corpus.ndjson",
            source_label="Cloud Logging sink export (aiplatform.googleapis.com audit logs)",
            config=VertexAdapterConfig(
                tenant_id=DEMO_TENANT_ID,
                container="saro-demo-audit-export",
                prefix="demo-tenant/",
            ),
            parse=vertex_parse,
        ),
    }


# ── Terminal rendering ───────────────────────────────────────────────────────


@dataclass
class Term:
    color: bool = True
    pace: float = 0.0
    out: Any = field(default_factory=lambda: sys.stdout)

    def _c(self, code: str, text: str) -> str:
        return f"\x1b[{code}m{text}\x1b[0m" if self.color else text

    def emit(self, line: str = "") -> None:
        print(line, file=self.out)
        if self.pace:
            self.out.flush()
            time.sleep(self.pace)

    def title(self, text: str) -> None:
        self.emit(self._c("1;36", text))

    def step(self, n: int, total: int, text: str) -> None:
        self.emit(self._c("1;33", f"[{n}/{total}] {text}"))

    def ok(self, text: str) -> None:
        self.emit(f"  {self._c('32', '✔')} {text}")

    def info(self, text: str) -> None:
        self.emit(f"    {text}")

    def warn(self, text: str) -> None:
        self.emit(f"  {self._c('33', '▲')} {text}")

    def sev(self, severity: str) -> str:
        codes = {"HIGH": "1;31", "MEDIUM": "33", "LOW": "36", "INFO": "2"}
        return self._c(codes.get(severity, "0"), severity)


# ── Pipeline stages ──────────────────────────────────────────────────────────


def _read_export(spec: ProviderSpec) -> list[str]:
    return [
        ln for ln in spec.corpus.read_text(encoding="utf-8").splitlines() if ln.strip()
    ]


def _parse_lines(
    spec: ProviderSpec, lines: list[str]
) -> tuple[list[NormalizedInvocationRecord], int, int]:
    """Parse every line; return (records, skipped_count, rejected_count)."""
    records: list[NormalizedInvocationRecord] = []
    skipped = rejected = 0
    for i, line in enumerate(lines, start=1):
        cursor = f"{spec.corpus.name}:L{i}"
        try:
            records.append(
                spec.parse(
                    line,
                    config=spec.config,
                    cursor=cursor,
                    source_uri=f"demo://{spec.config.container}/{spec.corpus.name}",
                )
            )
        except RecordSkipped:
            skipped += 1  # other category/service — not interpreted, never guessed
        except ExportRecordError:
            rejected += 1  # malformed — never turned into a half-populated record
    return records, skipped, rejected


def _availability_rollup(
    records: list[NormalizedInvocationRecord],
) -> dict[str, dict[str, int]]:
    fields = ("input_token_count", "output_token_count", "stop_reason", "model_id")
    rollup: dict[str, dict[str, int]] = {f: {} for f in fields}
    for rec in records:
        for f in fields:
            val = rec.availability(f).value
            rollup[f][val] = rollup[f].get(val, 0) + 1
    return rollup


def _body_free_proof() -> list[str]:
    """The contract's full field list — provably no content-bearing field."""
    return sorted(NormalizedInvocationRecord.model_fields.keys())


def _demo_packs(provider_key: str) -> list[ObservationPack]:
    packs = load_genesis_packs()
    out: list[ObservationPack] = []
    for ref in sorted(packs):
        pack = packs[ref]
        if pack.name == "RP-TOOL-SCOPE":
            pack = pack.with_allowed_tools(list(DEMO_ALLOWED_TOOLS[provider_key]))
        out.append(pack)
    return out


def _findings_rollup(findings: list[Finding]) -> dict[str, dict[str, Any]]:
    rollup: dict[str, dict[str, Any]] = {}
    for f in findings:
        row = rollup.setdefault(f.rule_id, {"severity": f.severity, "count": 0})
        row["count"] += 1
    return dict(sorted(rollup.items()))


# ── Demo run ─────────────────────────────────────────────────────────────────


def run_provider(spec: ProviderSpec, term: Term) -> dict[str, Any]:
    term.emit()
    term.title(f"━━ {spec.display} — export → adapter → rule packs → evidence ━━")

    term.step(1, 5, f"Read customer-owned export — {spec.source_label}")
    lines = _read_export(spec)
    # .as_posix(): the screencast is committed — output must not vary by OS
    term.ok(
        f"{len(lines)} log records read from "
        f"{spec.corpus.relative_to(_REPO_ROOT).as_posix()}"
    )
    term.info("read-only against customer storage — SARO holds no cloud write scope")

    term.step(2, 5, f"Adapter parse — {spec.adapter_id}")
    records, skipped, rejected = _parse_lines(spec, lines)
    term.ok(
        f"{len(records)} normalized · {skipped} skipped (other category/service) "
        f"· {rejected} rejected (malformed, never fabricated)"
    )
    sample = records[0]
    term.info(f"sample: request_id={sample.request_id}")
    term.info(
        f"        model_id={sample.model_id or '(missing)'} · "
        f"operation={sample.operation} · region={sample.region or '(missing)'}"
    )
    term.info(
        f"        tenant binding: operator-supplied ({sample.tenant_id}) — "
        "never read from the log"
    )

    term.step(3, 5, "Contract invariants — body-free by construction")
    fields = _body_free_proof()
    term.ok(f"contract fields ({len(fields)}): {', '.join(fields)}")
    term.info("no prompt, no completion, no tool arguments — content cannot reach")
    term.info("the record because the contract has no field able to hold it (INV-2)")
    rollup = _availability_rollup(records)
    for fname, counts in rollup.items():
        pretty = " · ".join(f"{k}={v}" for k, v in sorted(counts.items()))
        term.info(f"availability[{fname}]: {pretty}")

    term.step(4, 5, "Observation rule-pack evaluation")
    packs = _demo_packs(spec.key)
    for pack in packs:
        term.ok(f"{pack.pack_ref}  hash={pack.content_hash[:16]}…")
    term.info(f"tenant tool policy: allowed_tools={list(DEMO_ALLOWED_TOOLS[spec.key])}")
    findings = evaluate_records(records, packs)
    frollup = _findings_rollup(findings)
    for rule_id, row in frollup.items():
        term.emit(f"    {term.sev(row['severity']):<18} {rule_id:<28} ×{row['count']}")
    tool_hits = [f for f in findings if f.rule_id == "TOOL-SCOPE-VIOLATION-1"]
    if tool_hits:
        detail = tool_hits[0].detail
        term.warn(
            f"out-of-scope tool invoked: {detail['invoked_out_of_scope']} "
            f"(request {tool_hits[0].request_id})"
        )

    term.step(5, 5, "Evidence summary — for human auditor review")
    term.ok(
        f"{len(findings)} findings across {len(records)} invocations "
        f"→ TRACE-ready evidence records"
    )
    term.info("each finding carries rule id, pack hash, severity, remediation")
    term.info("guidance, and the request id that joins back to the source cursor")

    return {
        "provider": spec.display,
        "adapter_id": spec.adapter_id,
        "corpus": spec.corpus.relative_to(_REPO_ROOT).as_posix(),
        "records_read": len(lines),
        "records_normalized": len(records),
        "records_skipped": skipped,
        "records_rejected": rejected,
        "packs": [{"ref": p.pack_ref, "hash": p.content_hash} for p in packs],
        "findings_total": len(findings),
        "findings_by_rule": frollup,
        "availability": rollup,
    }


def main(argv: list[str]) -> int:
    # Windows consoles/pipes default to cp1252, which cannot encode the demo's
    # glyphs (✔ ▲ →) — force UTF-8 wherever the stream supports it (FND-087).
    for stream in (sys.stdout, sys.stderr):
        if hasattr(stream, "reconfigure"):
            try:
                stream.reconfigure(encoding="utf-8")
            except Exception:  # non-TextIOWrapper stand-ins (pytest capture)
                pass

    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--provider", choices=["azure", "vertex", "both"], default="both"
    )
    parser.add_argument("--azure-corpus", type=Path, default=None)
    parser.add_argument("--vertex-corpus", type=Path, default=None)
    parser.add_argument(
        "--json-out",
        type=Path,
        default=None,
        help="write the machine-readable summary here",
    )
    parser.add_argument("--no-color", action="store_true")
    parser.add_argument(
        "--pace",
        type=float,
        default=0.0,
        help="seconds to sleep per line (screen capture pacing)",
    )
    args = parser.parse_args(argv)

    term = Term(color=not args.no_color, pace=args.pace)

    specs = _provider_specs(args.azure_corpus, args.vertex_corpus)
    selected = ["azure", "vertex"] if args.provider == "both" else [args.provider]

    term.title("SARO — Azure OpenAI + Vertex AI end-to-end observation demo")
    term.emit(
        "Pipeline: customer log export → adapter → normalized record → "
        "rule packs → evidence"
    )
    term.emit(
        "Posture: read-only · body-free · zero external model calls in core scoring"
    )

    summaries = [run_provider(specs[key], term) for key in selected]

    term.emit()
    term.title("━━ Run summary ━━")
    for s in summaries:
        term.ok(
            f"{s['provider']:<14} {s['records_normalized']} records → "
            f"{s['findings_total']} evidence findings"
        )
    term.emit()
    term.emit(f"Disclaimer: {DISCLAIMER}")

    if args.json_out:
        args.json_out.parent.mkdir(parents=True, exist_ok=True)
        args.json_out.write_text(
            json.dumps({"providers": summaries, "disclaimer": DISCLAIMER}, indent=2)
            + "\n"
        )
        term.emit(f"JSON summary written: {args.json_out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
