#!/usr/bin/env python3
"""S-1107 — tenant-isolation security evidence pack.

Runs the isolation test suite, then renders a dated, commit-stamped PDF with a
pass/fail table to docs/evidence/. Intended to run weekly in CI (see
.github/workflows/security-evidence-weekly.yml) and on demand before an enterprise
review. This is *evidence generation* — interim proof of tenant isolation until an
external penetration test is funded (FB-020 / FB-028).

Usage:
  python scripts/generate_security_evidence.py [--output-dir docs/evidence] [--commit <sha>]

Exit 0 = all isolation checks passed; 1 = at least one failed (PDF still written).
"""
from __future__ import annotations

import argparse
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

from fpdf import FPDF, XPos, YPos

ROOT = Path(__file__).resolve().parent.parent

# (test node, human label) — the runnable isolation evidence.
_SUITE: list[tuple[str, str]] = [
    ("tests/test_pt009_tenant_isolation_concurrency.py",
     "No cross-tenant reads under 50 concurrent sessions"),
    ("tests/test_tenant_isolation.py",
     "Cross-tenant access denied (403) on traces / samples / reports"),
]

DISCLAIMER = (
    "This document is automated security evidence generated by SARO. It demonstrates "
    "tenant-isolation controls via the runnable test suite below and is interim evidence "
    "pending a funded third-party penetration test. It does not constitute a security "
    "certification. Human review by qualified personnel is required."
)


def _git_commit() -> str:
    try:
        out = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            cwd=ROOT, capture_output=True, text=True, timeout=15,
        )
        return out.stdout.strip() or "unknown"
    except Exception:
        return "unknown"


def _run_one(node: str) -> tuple[str, str]:
    """Run a single test node. Returns (status, detail)."""
    try:
        proc = subprocess.run(
            [sys.executable, "-m", "pytest", node, "-q", "--no-header", "--tb=line"],
            cwd=ROOT, capture_output=True, text=True, timeout=600,
        )
    except Exception as exc:  # pragma: no cover - environment failure
        return "ERROR", str(exc)[:120]
    summary = ""
    for line in reversed(proc.stdout.splitlines()):
        if "passed" in line or "failed" in line or "error" in line:
            summary = line.strip().strip("=").strip()
            break
    return ("PASS" if proc.returncode == 0 else "FAIL"), summary


def _ascii(text: str) -> str:
    return (text.replace("—", "-").replace("–", "-")
            .replace("'", "'").replace("'", "'").replace(""", '"').replace(""", '"')
            .encode("latin-1", errors="replace").decode("latin-1"))


def _render_pdf(rows: list[tuple[str, str, str, str]], commit: str, generated: str) -> bytes:
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    pdf.set_left_margin(20)
    pdf.set_right_margin(20)
    pdf.set_top_margin(20)

    pdf.set_font("Helvetica", "B", 15)
    pdf.set_text_color(26, 60, 94)
    pdf.multi_cell(0, 9, _ascii("SARO - Tenant Isolation Security Evidence"),
                   new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(2)

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(51, 51, 51)
    for k, v in (("Generated (UTC)", generated), ("Commit", commit),
                 ("Reference", "S-1107 / FB-020 / FB-028 (interim)")):
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(40, 7, _ascii(k + ":"), new_x=XPos.RIGHT, new_y=YPos.TOP)
        pdf.set_font("Helvetica", "", 10)
        pdf.multi_cell(0, 7, _ascii(v), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(4)

    # Results table
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(44, 95, 138)
    pdf.multi_cell(0, 7, "Isolation Test Results", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(1)
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(51, 51, 51)
    pdf.cell(22, 7, "Result", border=1)
    pdf.cell(0, 7, "Control", border=1, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("Helvetica", "", 9)
    for status_, label, node, summary in rows:
        color = (39, 80, 10) if status_ == "PASS" else (121, 31, 31)
        pdf.set_text_color(*color)
        pdf.cell(22, 7, status_, border=1)
        pdf.set_text_color(51, 51, 51)
        pdf.multi_cell(0, 7, _ascii(f"{label}  [{node} | {summary}]"),
                       border=1, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(4)

    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(136, 136, 136)
    pdf.multi_cell(0, 5, _ascii(DISCLAIMER), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    return bytes(pdf.output())


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate SARO tenant-isolation evidence PDF")
    parser.add_argument("--output-dir", default=str(ROOT / "docs" / "evidence"))
    parser.add_argument("--commit", default=None, help="commit sha to stamp (default: git HEAD)")
    args = parser.parse_args()

    out_dir = Path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    commit = args.commit or _git_commit()
    now = datetime.now(timezone.utc)
    generated = now.strftime("%Y-%m-%d %H:%M:%S UTC")

    rows: list[tuple[str, str, str, str]] = []
    all_pass = True
    for node, label in _SUITE:
        status_, summary = _run_one(node)
        if status_ != "PASS":
            all_pass = False
        rows.append((status_, label, node, summary))
        print(f"[{status_}] {label} ({node}) — {summary}")

    pdf_bytes = _render_pdf(rows, commit, generated)
    dated = out_dir / f"security-isolation-evidence-{now.strftime('%Y-%m-%d')}.pdf"
    latest = out_dir / "security-isolation-evidence-latest.pdf"
    dated.write_bytes(pdf_bytes)
    latest.write_bytes(pdf_bytes)
    print(f"\nEvidence written: {dated}  ({len(pdf_bytes):,} bytes)")
    print(f"Latest pointer  : {latest}")
    return 0 if all_pass else 1


if __name__ == "__main__":
    sys.exit(main())
