"""
Generate governance PDF documents for CF-05 Governance Trust Page.
Run once: python scripts/generate_governance_pdfs.py
Uses fpdf2 (pure Python — no external system dependencies).
"""
from __future__ import annotations

import sys
from pathlib import Path

from fpdf import FPDF, XPos, YPos

ROOT = Path(__file__).parent.parent
DOCS_DIR = ROOT / "docs"
DOCS_DIR.mkdir(exist_ok=True)

DISCLAIMER = (
    "This document is audit evidence generated by SARO v8.0.0. It does not constitute "
    "regulatory certification, legal advice, or compliance approval. Human review and "
    "sign-off by qualified personnel is required before any regulatory submission."
)


def _ascii(text: str) -> str:
    """Replace non-latin-1 chars with safe ASCII equivalents."""
    return (text
            .replace("—", "-").replace("–", "-")
            .replace("‘", "'").replace("’", "'")
            .replace("“", '"').replace("”", '"')
            .replace("•", "-")
            .encode("latin-1", errors="replace").decode("latin-1"))


def _make_pdf(title: str, sections: list[tuple[str, str]], meta: dict) -> bytes:
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    pdf.set_left_margin(20)
    pdf.set_right_margin(20)
    pdf.set_top_margin(20)

    # Title
    pdf.set_font("Helvetica", "B", 15)
    pdf.set_text_color(26, 60, 94)
    pdf.multi_cell(0, 9, _ascii(title), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(2)

    # Metadata
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(51, 51, 51)
    for key, val in meta.items():
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(50, 7, _ascii(key + ":"), new_x=XPos.RIGHT, new_y=YPos.TOP)
        pdf.set_font("Helvetica", "", 10)
        pdf.multi_cell(0, 7, _ascii(val), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(4)

    # Sections
    for section_title, body in sections:
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(44, 95, 138)
        pdf.multi_cell(0, 7, _ascii(section_title), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(51, 51, 51)
        pdf.multi_cell(0, 6, _ascii(body), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.ln(3)

    # Disclaimer
    pdf.ln(4)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(136, 136, 136)
    pdf.multi_cell(0, 5, _ascii(DISCLAIMER), new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    return bytes(pdf.output())


def generate_nist_pdf() -> Path:
    out = DOCS_DIR / "saro-nist-ai-rmf-self-assessment-v1.0.pdf"
    content = _make_pdf(
        title="SARO v8.0.0 - NIST AI RMF 1.0 Self-Assessment",
        meta={
            "Document Version": "1.0.0",
            "Last Reviewed": "2026-05-21",
            "Reviewer": "Venky (Lead Engineer) & Jordan Lee (Backend/Infra)",
            "Rule Pack Reference": "nist-ai-rmf@1.0.0",
        },
        sections=[
            ("Executive Summary",
             "SARO (Smart AI Risk Orchestrator) is an AI risk auditing platform providing "
             "evidence-based risk scoring and audit trail generation. This document is SARO's "
             "self-assessment against the NIST AI RMF 1.0. It does not constitute external certification."),
            ("GOVERN 1.1 - Policies and Procedures",
             "SARO operates under the SARO Compliance Claims Matrix (v8.0.0), defining what SARO "
             "does and does not claim. All audit outputs carry mandatory disclaimers per AIGP "
             "human-in-the-loop requirements."),
            ("GOVERN 4.2 - Privacy Risk Management",
             "SARO never stores raw prompt text beyond the audit session. PII detected during Gate 3 "
             "is flagged but not persisted in retrievable form. TRACE records store only anonymised "
             "signal metadata."),
            ("MAP 1.1 - Context Establishment",
             "SARO's 4-gate pipeline is scoped to risk scoring and evidence generation only. It does "
             "not make deployment decisions, write to client systems, or certify AI systems."),
            ("MAP 2.3 - Fairness Scientific Findings",
             "Gate 2 applies statistical parity difference analysis across demographic groups. "
             "Thresholds: 0.10 (warn), 0.20 (fail) per NIST MAP 2.3 guidance. Versioned rule pack "
             "nist-ai-rmf@1.0.0 implements this with CI-tested known-positive and known-negative "
             "fixtures."),
            ("MEASURE 2.5 - Robustness and Reliability",
             "SARO implements Bayesian risk scoring (Beta-Binomial posterior, 95% credible intervals), "
             "MIT taxonomy keyword+regex detection across 7 risk domains, and TF-IDF cosine similarity "
             "against historical AI incidents. Rule nist-ai-rmf@1.0.0 maps Misinformation to "
             "MEASURE 2.5."),
            ("MEASURE 2.6 - TEVV Cycles",
             "The SARO CI pipeline runs known-positive and known-negative fixture tests for every "
             "rule pack rule on every deployment — automated TEVV per NIST MEASURE 2.6."),
            ("MANAGE 4.1 - Residual Risk Treatment",
             "SARO outputs residual risk scores and remediation guidance per MIT domain. Human "
             "operators must review and sign off via the TRACE Remedy workflow. SARO does not "
             "auto-remediate or modify client AI systems."),
        ],
    )
    out.write_bytes(content)
    return out


def generate_eu_pdf() -> Path:
    out = DOCS_DIR / "saro-eu-ai-act-position-v1.0.pdf"
    content = _make_pdf(
        title="SARO v8.0.0 - EU AI Act Position Statement",
        meta={
            "Document Version": "1.0.0",
            "Last Reviewed": "2026-05-21",
            "Reviewer": "Venky (Lead Engineer)",
            "Rule Pack Reference": "eu-ai-act@1.0.0",
        },
        sections=[
            ("Scope of This Statement",
             "This document describes SARO's position with respect to the EU AI Act "
             "(Regulation (EU) 2024/1689). It supports enterprise procurement teams and "
             "compliance officers evaluating SARO for EU-regulated environments."),
            ("Explicit Boundaries - SARO Does NOT:",
             "- perform conformity assessments under the EU AI Act\n"
             "- issue compliance certifications or declarations of conformity\n"
             "- replace a human compliance officer or notified body assessment\n"
             "- classify AI systems under Annex I or Annex III of the EU AI Act\n"
             "- make legal determinations about an AI system's regulatory status"),
            ("Article 10 - Data and Data Governance",
             "SARO Gate 2 (Fairness) implements statistical parity analysis to support Article 10 "
             "compliance documentation. Rule pack eu-ai-act@1.0.0 maps detections to ART_10 "
             "and ART_10_3 obligations. Human review required for remediation."),
            ("Article 50 - Transparency Obligations",
             "SARO detects indicators of synthetic content (Misinformation domain) and maps to "
             "ART_50 transparency obligations. SARO generates evidence that transparency disclosures "
             "may be required; it does not create or verify transparency labels."),
            ("Article 9 - Risk Management System",
             "SARO's 4-gate pipeline provides structured risk evidence supporting Article 9 risk "
             "management documentation. The TRACE timeline is an immutable audit record."),
            ("SARO Classification Under the EU AI Act",
             "General Purpose AI (GPAI)? No - SARO is a specialised audit tool.\n"
             "High-Risk System (Annex III)? SARO does not make decisions affecting persons.\n"
             "Prohibited Practice (Article 5)? Not applicable - SARO is read-only analysis.\n"
             "Transparency (Article 50)? Audit reports carry mandatory disclaimers."),
            ("Approved Language per Compliance Claims Matrix",
             "Approved: 'Indicators consistent with EU AI Act high-risk criteria'.\n"
             "Forbidden: 'SARO certifies compliance', 'EU AI Act compliant', 'NIST Certified'."),
        ],
    )
    out.write_bytes(content)
    return out


if __name__ == "__main__":
    p1 = generate_nist_pdf()
    print(f"Generated: {p1} ({p1.stat().st_size:,} bytes)")
    p2 = generate_eu_pdf()
    print(f"Generated: {p2} ({p2.stat().st_size:,} bytes)")
