"""
S-000: SARO Demo Tenant Seed Script
=====================================
Idempotent one-time setup script.  Creates the demo tenant, populates it with
seed AI output audits across all four verticals, and verifies the pipeline end-
to-end before any client demo.

Usage:
    python scripts/seed_demo_tenant.py \
        --database-url $DATABASE_URL \
        --saro-url https://saro-platform.fly.dev

Writes credentials to .env.demo (gitignored).
"""
from __future__ import annotations

import argparse
import os
import sys
import time
import uuid

import requests
import structlog
from sqlalchemy import create_engine, text
from sqlalchemy.orm import sessionmaker

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

log = structlog.get_logger()

DEMO_TENANT_NAME  = "SARO Demo Tenant"
DEMO_TENANT_SLUG  = "saro-demo"
DEMO_USER_EMAIL   = "demo@saro-platform.io"
DEMO_USER_PW      = "SaroDemo2026!"

VERTICALS = ["finance", "healthcare", "technology", "government"]

SEED_PAYLOADS: dict[str, list[dict]] = {
    "finance": [
        {
            "prompt": "Assess credit risk for applicant with DTI 0.45 and credit score 680.",
            "output": (
                "Based on DTI ratio of 0.45 and credit score 680, risk classification is MODERATE. "
                "Recommend additional collateral review per SR 11-7 guidelines."
            ),
        },
        {
            "prompt": "Explain the loan denial decision for application ID 88421.",
            "output": (
                "Application 88421 denied due to: (1) DTI exceeds 43% threshold, "
                "(2) insufficient credit history. SHAP explanation: DTI contributed 0.61 to denial score."
            ),
        },
        {
            "prompt": "What is the fair lending risk in this mortgage portfolio?",
            "output": (
                "Disparate impact ratio for minority applicants: 1.19 (threshold 1.15). "
                "Flag for HMDA compliance review. Recommend model audit per NIST AI RMF MEASURE-2.5."
            ),
        },
    ],
    "healthcare": [
        {
            "prompt": "Patient presents with chest pain, shortness of breath, age 58. Recommend triage priority.",
            "output": (
                "PRIORITY 1 — Immediate assessment required. Differential: ACS, PE, aortic dissection. "
                "Initiate ECG and troponin. SHAP: age and symptom combination = high acuity score 0.89."
            ),
        },
        {
            "prompt": "Summarise treatment plan for Type 2 diabetes patient, HbA1c 9.2%.",
            "output": (
                "Recommend: Metformin 1000mg BID, dietary counselling, 3-month HbA1c recheck. "
                "Model confidence: 0.84. Note: Recommendation generated by AI — physician review required."
            ),
        },
    ],
    "technology": [
        {
            "prompt": "Moderate this user comment: 'You people are all the same.'",
            "output": (
                "FLAG: Potential identity-based generalisation detected. Toxicity score: 0.71 (threshold 0.65). "
                "Recommend human review before publish. eKYC injection scan: clean."
            ),
        },
        {
            "prompt": "Review this API response for PII exposure.",
            "output": (
                "PII detected: email address pattern at position 142. "
                "GDPR Article 22 automated decision flag. Recommend masking before logging. Risk score: 0.88."
            ),
        },
    ],
    "government": [
        {
            "prompt": "Assess this benefits determination AI output for fairness.",
            "output": (
                "Benefits determination output reviewed. Age-group disparity ratio: 1.08 (within 1.15 threshold). "
                "NIST AI RMF GOVERN-1.1 evidence record created. EO 14110 compliance: PASS."
            ),
        },
        {
            "prompt": "Review procurement recommendation for compliance with federal AI policy.",
            "output": (
                "Procurement AI recommendation reviewed per EO 14110. Human oversight requirement: SATISFIED. "
                "Audit trail: complete. NIST RMF mapping: MAP-1.5, MANAGE-3.2."
            ),
        },
    ],
}


# ── Step 1: Create or retrieve demo tenant ────────────────────────────────────


def get_or_create_demo_tenant(session) -> dict:
    row = session.execute(
        text("SELECT id FROM tenants WHERE slug = :slug LIMIT 1"),
        {"slug": DEMO_TENANT_SLUG},
    ).fetchone()
    if row:
        log.info("demo_tenant_exists", tenant_id=str(row[0]))
        return {"tenant_id": str(row[0]), "created": False}

    tenant_id = uuid.uuid4()
    session.execute(
        text("INSERT INTO tenants (id, name, slug, created_at) VALUES (:id, :name, :slug, NOW())"),
        {"id": tenant_id, "name": DEMO_TENANT_NAME, "slug": DEMO_TENANT_SLUG},
    )
    # Hash password with pgcrypto; fall back to plain if extension not available
    try:
        session.execute(
            text(
                "INSERT INTO users (id, tenant_id, email, hashed_password, role, is_active, created_at) "
                "VALUES (gen_random_uuid(), :tid, :email, crypt(:pw, gen_salt('bf')), 'super_admin', true, NOW())"
            ),
            {"tid": tenant_id, "email": DEMO_USER_EMAIL, "pw": DEMO_USER_PW},
        )
    except Exception:
        session.rollback()
        # pgcrypto not available — use Python argon2
        from argon2 import PasswordHasher
        hashed = PasswordHasher().hash(DEMO_USER_PW)
        session.execute(
            text(
                "INSERT INTO users (id, tenant_id, email, hashed_password, role, is_active, created_at) "
                "VALUES (gen_random_uuid(), :tid, :email, :pw, 'super_admin', true, NOW())"
            ),
            {"tid": tenant_id, "email": DEMO_USER_EMAIL, "pw": hashed},
        )
    session.execute(
        text(
            "INSERT INTO client_configs (id, tenant_id, industry, created_at) "
            "VALUES (gen_random_uuid(), :tid, 'multi_vertical', NOW()) "
            "ON CONFLICT (tenant_id) DO NOTHING"
        ),
        {"tid": tenant_id},
    )
    session.commit()
    log.info("demo_tenant_created", tenant_id=str(tenant_id))
    return {"tenant_id": str(tenant_id), "created": True}


# ── Step 2: Obtain JWT ────────────────────────────────────────────────────────


def get_demo_jwt(saro_url: str) -> str:
    resp = requests.post(
        f"{saro_url}/api/v1/auth/token",
        data={"username": DEMO_USER_EMAIL, "password": DEMO_USER_PW},
        timeout=15,
    )
    resp.raise_for_status()
    token = resp.json().get("access_token") or resp.json().get("token")
    if not token:
        raise ValueError(f"No token in login response: {resp.json()}")
    log.info("demo_jwt_obtained")
    return token


# ── Step 3: Ingest seed payloads ──────────────────────────────────────────────


def ingest_seed_payloads(saro_url: str, token: str, tenant_id: str) -> dict:
    headers = {"Authorization": f"Bearer {token}", "Content-Type": "application/json"}
    results: dict = {"success": 0, "failed": 0, "audit_ids": []}

    for vertical, payloads in SEED_PAYLOADS.items():
        for p in payloads:
            try:
                resp = requests.post(
                    f"{saro_url}/api/v1/ingest",
                    json={
                        "source_model":     "internal",
                        "prompt_text":      p["prompt"],
                        "raw_output_text":  p["output"],
                        "vertical":         vertical,
                        "tenant_id":        tenant_id,
                        "ingestion_method": "api",
                    },
                    headers=headers,
                    timeout=15,
                )
                if resp.status_code == 201:
                    results["success"] += 1
                    results["audit_ids"].append(resp.json()["audit_id"])
                else:
                    results["failed"] += 1
                    log.warning("ingest_failed", status=resp.status_code, body=resp.text[:200])
            except Exception as exc:
                results["failed"] += 1
                log.error("ingest_error", error=str(exc))
            time.sleep(0.2)

    return results


# ── Step 4: Wait for engine ───────────────────────────────────────────────────


def wait_for_audits(saro_url: str, token: str, audit_ids: list, timeout_s: int = 120) -> dict:
    headers  = {"Authorization": f"Bearer {token}"}
    deadline = time.time() + timeout_s
    pending  = set(audit_ids)
    completed = failed = 0

    while pending and time.time() < deadline:
        time.sleep(2)
        for aid in list(pending):
            try:
                resp = requests.get(
                    f"{saro_url}/api/v1/ingest/{aid}",
                    headers=headers, timeout=10,
                )
                s = resp.json().get("status")
                if s == "completed":
                    completed += 1
                    pending.discard(aid)
                elif s == "failed":
                    failed += 1
                    pending.discard(aid)
            except Exception:
                pass

    return {"completed": completed, "failed": failed, "timed_out": len(pending)}


# ── Step 5: Write .env.demo ───────────────────────────────────────────────────


def write_env_demo(tenant_id: str, token: str, saro_url: str) -> None:
    with open(".env.demo", "w") as f:
        f.write(f"SARO_DEMO_TENANT_ID={tenant_id}\n")
        f.write(f"SARO_DEMO_TOKEN={token}\n")
        f.write(f"SARO_DEMO_URL={saro_url}\n")
    log.info("env_demo_written", path=".env.demo")


# ── Step 6: Verify dashboard ──────────────────────────────────────────────────


def verify_dashboard(saro_url: str, token: str) -> bool:
    headers = {"Authorization": f"Bearer {token}"}
    resp = requests.get(f"{saro_url}/api/v1/dashboard/kpis", headers=headers, timeout=10)
    data = resp.json()
    count = data.get("total_audits", 0) or data.get("audit_count", 0)
    log.info("dashboard_verified", total_audits=count)
    return count > 0


# ── Main ──────────────────────────────────────────────────────────────────────


def main() -> None:
    parser = argparse.ArgumentParser(description="SARO Demo Tenant Seed Script")
    parser.add_argument("--database-url", default=os.getenv("DATABASE_URL"))
    parser.add_argument("--saro-url", default="https://saro-platform.fly.dev")
    args = parser.parse_args()

    if not args.database_url:
        log.error("DATABASE_URL required")
        sys.exit(1)

    eng     = create_engine(args.database_url)
    Session = sessionmaker(bind=eng)

    print("\n=== SARO Demo Tenant Seed Script ===")

    print("Step 1: Create or retrieve demo tenant...")
    with Session() as session:
        tenant = get_or_create_demo_tenant(session)
    print(f"  Tenant ID: {tenant['tenant_id']} (created={tenant['created']})")

    print("Step 2: Obtain JWT...")
    token = get_demo_jwt(args.saro_url)

    print("Step 3: Ingest seed payloads...")
    results = ingest_seed_payloads(args.saro_url, token, tenant["tenant_id"])
    print(f"  Ingested: {results['success']} / Failed: {results['failed']}")

    print("Step 4: Waiting for engine (up to 120s)...")
    completion = wait_for_audits(args.saro_url, token, results["audit_ids"])
    print(
        f"  Completed: {completion['completed']}  "
        f"Failed: {completion['failed']}  "
        f"Timed out: {completion['timed_out']}"
    )

    print("Step 5: Writing .env.demo...")
    write_env_demo(tenant["tenant_id"], token, args.saro_url)

    print("Step 6: Verifying dashboard...")
    ok = verify_dashboard(args.saro_url, token)
    if not ok:
        print("  WARNING: Dashboard shows 0 audits — check engine logs")
    else:
        print("  Dashboard verified — demo tenant is ready")

    print("\n=== SEED COMPLETE ===")
    print(f"Demo tenant ID : {tenant['tenant_id']}")
    print(f"Demo URL       : {args.saro_url}/demo")
    print("Credentials    : .env.demo")
    print("Next step      : Add SARO_DEMO_TENANT_ID to GitHub / Fly.io secrets")


if __name__ == "__main__":
    main()
