"""Board-level risk dashboard API endpoints."""
import hashlib
import hmac
import io
import json
import os
from datetime import datetime, timedelta

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session

from auth import get_current_user
from database import get_db
from models import Audit, AuditTrace, ScanReport, Tenant
from services.risk_service import (
    aggregate_vendor_risk,
    build_risk_summary,
    calculate_rag_status,
)

router = APIRouter(prefix="/api/v1", tags=["risk-dashboard"])

_HMAC_SECRET = os.environ.get("SARO_EXPORT_SECRET", "saro-default-export-secret")
_BOARD_RED_THRESHOLD = float(os.environ.get("BOARD_RISK_RED_THRESHOLD", "0.7"))
_BOARD_AMBER_THRESHOLD = float(os.environ.get("BOARD_RISK_AMBER_THRESHOLD", "0.4"))

# Required on every exported report — docs/COMPLIANCE_CLAIMS_MATRIX.md ("Required
# Disclaimer (all reports)"). Defined once so both PDF exporters stay in sync.
_REPORT_DISCLAIMER = (
    "This report is audit evidence generated by SARO v8.0.0. It does not constitute "
    "regulatory certification, legal advice, or compliance approval. Human review and "
    "sign-off by qualified personnel is required before any regulatory submission."
)

# EVF Tier-3 status (docs/COMPLIANCE_CLAIMS_MATRIX.md — SARO-RISK-001): no framework
# claim has completed External SME Validation, so no coverage percentage may be
# published in external materials. Replaces the previously hardcoded fake percentages.
_EVF_FRAMEWORK_STATUS = "Internal Review Only — Not for External Claim (EVF SARO-RISK-001)"

_SEVERITY_BY_RESULT = {"fail": 3, "triggered": 3, "flagged": 2, "warn": 1, "pass": 0}


def _severity_rank(result: str) -> int:
    """Map a trace result to a numeric severity for finding aggregation."""
    return _SEVERITY_BY_RESULT.get((result or "").lower(), 1)


def _get_finding_records(db: Session, audit_ids: list) -> list[dict]:
    """Fetch open/remediated findings (failing traces) for the given audits.

    Returns dicts shaped for ``services.risk_service.build_risk_summary``:
    ``status`` is "open" | "remediated" and ``severity`` is a numeric rank. This
    replaces the previous ``findings=[]`` hardcode that forced every
    finding-derived metric (top_findings, remediation_pct, open count) to zero.
    """
    if not audit_ids:
        return []
    traces = (
        db.query(AuditTrace)
        .filter(
            AuditTrace.audit_id.in_(audit_ids),
            AuditTrace.result.in_(["fail", "warn", "flagged", "triggered"]),
        )
        .all()
    )
    return [
        {
            "id": str(t.id),
            "check_name": t.check_name,
            "domain": t.check_name,
            "result": t.result,
            "reason": (t.reason or "")[:200],
            "status": "remediated" if t.is_remediated else "open",
            "severity": _severity_rank(t.result),
        }
        for t in traces
    ]


def _get_audit_records(db: Session, tenant_id) -> list[dict]:
    """Fetch audit records with risk scores for a tenant."""
    rows = (
        db.query(Audit, ScanReport)
        .join(ScanReport, ScanReport.audit_id == Audit.id, isouter=True)
        .filter(Audit.tenant_id == tenant_id)
        .all()
    )
    records = []
    for audit, report in rows:
        records.append({
            "audit_id": audit.id,
            "created_at": str(audit.created_at),
            "status": audit.status,
            "risk_score": getattr(report, "risk_score", None) if report else None,
            "confidence": getattr(report, "confidence", None) if report else None,
            "source_model": getattr(audit, "source_model", None),
        })
    return records


@router.get("/risk/summary")
def get_risk_summary(
    db: Session = Depends(get_db),
    current_user=Depends(get_current_user),
):
    """Return aggregated risk summary for the board dashboard."""
    records = _get_audit_records(db, current_user.tenant_id)
    findings = _get_finding_records(db, [r["audit_id"] for r in records])
    return build_risk_summary(records, findings=findings)


@router.get("/risk/vendors")
def get_vendor_risk(
    db: Session = Depends(get_db),
    current_user=Depends(get_current_user),
):
    """Return risk breakdown by AI vendor/model."""
    records = _get_audit_records(db, current_user.tenant_id)
    return {
        "vendors": aggregate_vendor_risk(records),
        "total_vendors": len(set(r.get("source_model") or "Unknown" for r in records)),
    }


@router.get("/risk/whats-changed")
def get_whats_changed(
    db: Session = Depends(get_db),
    current_user=Depends(get_current_user),
):
    """Return 7-day risk delta: score change, new audits, new findings vs. prior 7 days."""
    all_records = _get_audit_records(db, current_user.tenant_id)
    now = datetime.utcnow()
    cutoff_7 = now - timedelta(days=7)
    cutoff_14 = now - timedelta(days=14)

    def _score(records: list[dict]) -> float:
        scores = [r["risk_score"] for r in records if r.get("risk_score") is not None]
        return round(sum(scores) / len(scores), 2) if scores else 0.0

    def _in_window(r: dict, start: datetime, end: datetime) -> bool:
        try:
            dt = datetime.fromisoformat(str(r["created_at"]).split(".")[0].rstrip("Z"))
            return start <= dt <= end
        except Exception:
            return False

    recent = [r for r in all_records if _in_window(r, cutoff_7, now)]
    prior = [r for r in all_records if _in_window(r, cutoff_14, cutoff_7)]

    recent_score = _score(recent)
    prior_score = _score(prior)
    delta = round(recent_score - prior_score, 2)

    return {
        "period_days": 7,
        "current_avg_score": recent_score,
        "prior_avg_score": prior_score,
        "score_delta": delta,
        "delta_direction": "up" if delta > 0 else ("down" if delta < 0 else "flat"),
        "new_audits_count": len(recent),
        "prior_audits_count": len(prior),
        "current_rag": calculate_rag_status(recent_score),
        "prior_rag": calculate_rag_status(prior_score),
        "generated_at": now.isoformat(),
    }


@router.get("/risk/board-export")
def export_board_pdf(
    db: Session = Depends(get_db),
    current_user=Depends(get_current_user),
):
    """Generate a board-ready one-page risk summary PDF with vendor risk section."""
    _require_board_access(current_user)
    records = _get_audit_records(db, current_user.tenant_id)
    findings = _get_finding_records(db, [r["audit_id"] for r in records])
    summary = build_risk_summary(records, findings=findings)
    vendors = aggregate_vendor_risk(records)

    try:
        from reportlab.lib import colors
        from reportlab.lib.pagesizes import letter
        from reportlab.lib.styles import getSampleStyleSheet
        from reportlab.lib.units import inch
        from reportlab.platypus import (
            Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle,
        )

        buf = io.BytesIO()
        doc = SimpleDocTemplate(buf, pagesize=letter,
                                leftMargin=inch, rightMargin=inch,
                                topMargin=inch, bottomMargin=inch)
        styles = getSampleStyleSheet()
        story = []

        # ── Header ───────────────────────────────────────────────────────────
        story.append(Paragraph("SARO Board Risk Summary", styles["Title"]))
        story.append(Paragraph(
            f"Generated: {datetime.utcnow().strftime('%d %B %Y')} | "
            f"Audits analysed: {summary['audit_count']}",
            styles["Normal"],
        ))
        story.append(Spacer(1, 12))

        # ── RAG Status ───────────────────────────────────────────────────────
        rag = summary["rag_status"]
        rag_color = {"GREEN": colors.green, "AMBER": colors.orange, "RED": colors.red}.get(rag, colors.grey)
        rag_table = Table([[f"Overall Risk Status: {rag}  |  Score: {summary['overall_risk_score']}"]])
        rag_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), rag_color),
            ("TEXTCOLOR", (0, 0), (-1, -1), colors.white),
            ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 14),
            ("ALIGN", (0, 0), (-1, -1), "CENTER"),
            ("TOPPADDING", (0, 0), (-1, -1), 8),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ]))
        story.append(rag_table)
        story.append(Spacer(1, 16))

        # ── Vendor Risk ──────────────────────────────────────────────────────
        story.append(Paragraph("AI Vendor Risk Breakdown", styles["Heading2"]))
        if vendors:
            vdata = [["Vendor / Model", "Audits", "Avg Score", "Status", "New?"]]
            for v in vendors:
                vdata.append([
                    v["vendor"],
                    str(v["audit_count"]),
                    str(v["avg_risk_score"]),
                    v["rag_status"],
                    "⚠️ New" if v.get("is_new") else "—",
                ])
            vtable = Table(vdata, colWidths=[2.5 * inch, 0.8 * inch, 1 * inch, 1 * inch, 0.8 * inch])
            vtable.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e3a5f")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f1f5f9")]),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("TOPPADDING", (0, 0), (-1, -1), 5),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ]))
            story.append(vtable)
        else:
            story.append(Paragraph("No vendor data available.", styles["Normal"]))
        story.append(Spacer(1, 16))

        # ── Remediation % ────────────────────────────────────────────────────
        story.append(Paragraph(
            f"Remediation Progress: {summary['remediation_pct']}%", styles["Heading3"],
        ))
        story.append(Spacer(1, 12))

        # ── Verification hash ────────────────────────────────────────────────
        canonical = json.dumps(
            {"tenant_id": str(current_user.tenant_id), "generated_at": summary["generated_at"]},
            sort_keys=True,
        )
        sig = hmac.new(_HMAC_SECRET.encode(), canonical.encode(), hashlib.sha256).hexdigest()
        story.append(Paragraph(f"Verification hash: {sig[:24]}…", styles["Normal"]))

        # Required compliance disclaimer on every exported report (FND-018).
        story.append(Spacer(1, 12))
        story.append(Paragraph(_REPORT_DISCLAIMER, styles["Italic"]))

        doc.build(story)
        buf.seek(0)

        return StreamingResponse(
            buf,
            media_type="application/pdf",
            headers={"Content-Disposition": "attachment; filename=saro-board-risk-report.pdf"},
        )

    except ImportError:
        # ReportLab not installed — return JSON summary instead
        return {
            **summary,
            "vendors": vendors,
            "note": "Install reportlab for PDF export: pip install reportlab",
        }


# ── SPEC-FE2: Board RAG Summary endpoints ────────────────────────────────────


def _require_board_access(current_user) -> None:
    """SPEC-FE2 FR-06: require risk_officer or super_admin."""
    allowed_personas = {"risk_officer", "super_admin"}
    if current_user.role == "super_admin":
        return
    if current_user.persona_role in allowed_personas:
        return
    raise HTTPException(status_code=403, detail="Board summary requires risk_officer or super_admin role")


@router.get("/risk-dashboard/board-summary", summary="Board-ready RAG risk summary (SPEC-FE2)")
def get_board_summary(
    db: Session = Depends(get_db),
    current_user=Depends(get_current_user),
) -> dict:
    """
    Aggregated tenant-level risk data for the board view.
    RBAC: risk_officer and super_admin only.
    """
    _require_board_access(current_user)

    cutoff = datetime.utcnow() - timedelta(days=90)
    rows = (
        db.query(Audit, ScanReport)
        .join(ScanReport, ScanReport.audit_id == Audit.id, isouter=True)
        .filter(
            Audit.tenant_id == current_user.tenant_id,
            Audit.status == "completed",
            Audit.created_at >= cutoff,
        )
        .all()
    )

    if not rows:
        return {
            "rag_status": "No data",
            "overall_risk_score": None,
            "top_findings": [],
            "remediation_progress": {"total": 0, "remediated": 0, "percentage": 0.0},
            "framework_coverage": {},
            "trend_data": [],
            "generated_at": datetime.utcnow().isoformat(),
            "note": "No completed audits in the last 90 days.",
        }

    scores = [
        r.overall_risk_score
        for _, r in rows
        if r and r.overall_risk_score is not None
    ]
    max_score = max(scores) if scores else 0.0
    avg_score = round(sum(scores) / len(scores), 3) if scores else 0.0

    if max_score > _BOARD_RED_THRESHOLD:
        rag = "RED"
    elif max_score > _BOARD_AMBER_THRESHOLD:
        rag = "AMBER"
    else:
        rag = "GREEN"

    audit_ids = [a.id for a, _ in rows]

    # Top 3 unmediated critical findings
    top_traces = (
        db.query(AuditTrace)
        .filter(
            AuditTrace.audit_id.in_(audit_ids),
            AuditTrace.result.in_(["fail", "flagged", "triggered"]),
            AuditTrace.is_remediated.is_(False),
        )
        .order_by(AuditTrace.gate_id)
        .limit(3)
        .all()
    )
    top_findings = [
        {
            "id": str(t.id),
            "check_name": t.check_name,
            "result": t.result,
            "reason": (t.reason or "")[:200],
            "domain": t.check_name,
        }
        for t in top_traces
    ]

    # Remediation progress
    all_traces = (
        db.query(AuditTrace)
        .filter(
            AuditTrace.audit_id.in_(audit_ids),
            AuditTrace.result.in_(["fail", "warn", "flagged", "triggered"]),
        )
        .all()
    )
    total_traces = len(all_traces)
    remediated_count = sum(1 for t in all_traces if t.is_remediated)
    rem_pct = round(remediated_count / total_traces * 100, 1) if total_traces else 0.0

    # Framework coverage: EVF Tier-3 (SARO-RISK-001) — no framework claim has
    # completed External SME Validation, so no coverage percentage may be
    # published. The previous hardcoded percentages were a fabricated external
    # claim (FND-019). Report scope + EVF status only, never a numeric %.
    framework_coverage = {
        fw: _EVF_FRAMEWORK_STATUS
        for fw in ("EU AI Act", "NIST AI RMF", "AIGP", "ISO 42001")
    }

    # Trend data: last 12 audits
    trend = [
        {
            "audit_id": str(a.id),
            "created_at": a.created_at.isoformat() if a.created_at else None,
            "risk_score": r.overall_risk_score if r else None,
        }
        for a, r in sorted(rows, key=lambda x: x[0].created_at or datetime.min)[-12:]
    ]

    return {
        "rag_status": rag,
        "overall_risk_score": avg_score,
        "top_findings": top_findings,
        "remediation_progress": {
            "total": total_traces,
            "remediated": remediated_count,
            "percentage": rem_pct,
        },
        "framework_coverage": framework_coverage,
        "trend_data": trend,
        "generated_at": datetime.utcnow().isoformat(),
    }


@router.get(
    "/risk-dashboard/board-summary/export.pdf",
    summary="Single-page PDF board report (SPEC-FE2 FR-07)",
)
def export_board_summary_pdf(
    db: Session = Depends(get_db),
    current_user=Depends(get_current_user),
):
    """Generate a single-page PDF board report suitable for board pack insertion."""
    _require_board_access(current_user)
    summary = get_board_summary(db=db, current_user=current_user)

    if summary.get("rag_status") == "No data":
        raise HTTPException(status_code=400, detail="No completed audits in the last 90 days — PDF export disabled")

    try:
        from reportlab.lib import colors
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
        from reportlab.lib.units import cm
        from reportlab.platypus import (
            HRFlowable, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle,
        )

        buf = io.BytesIO()
        doc = SimpleDocTemplate(
            buf, pagesize=A4,
            leftMargin=1.5 * cm, rightMargin=1.5 * cm,
            topMargin=1.5 * cm, bottomMargin=2 * cm,
        )
        styles = getSampleStyleSheet()
        story = []

        tenant = db.query(Tenant).filter(Tenant.id == current_user.tenant_id).first()
        tenant_name = tenant.name if tenant else "Unknown"

        story.append(Paragraph("<b>SARO</b> — AI Risk Board Summary", styles["Title"]))
        story.append(
            Paragraph(
                f"{tenant_name} | {datetime.utcnow().strftime('%d %B %Y')}",
                styles["Normal"],
            )
        )
        story.append(Spacer(1, 10))

        rag = summary.get("rag_status", "No data")
        rag_color_map = {"RED": colors.red, "AMBER": colors.orange, "GREEN": colors.green}
        rag_color = rag_color_map.get(rag, colors.grey)
        score_val = summary.get("overall_risk_score", "N/A")
        rag_table = Table(
            [[f"Overall Risk: {rag}  |  Score: {score_val}"]],
            colWidths=[15 * cm],
        )
        rag_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), rag_color),
            ("TEXTCOLOR", (0, 0), (-1, -1), colors.white),
            ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 16),
            ("ALIGN", (0, 0), (-1, -1), "CENTER"),
            ("TOPPADDING", (0, 0), (-1, -1), 12),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 12),
        ]))
        story.append(rag_table)
        story.append(Spacer(1, 10))

        story.append(Paragraph("Top Risk Findings (Last 90 Days)", styles["Heading2"]))
        findings = summary.get("top_findings", [])
        if findings:
            for i, f in enumerate(findings, 1):
                story.append(
                    Paragraph(
                        f"{i}. <b>{f.get('check_name', '—')}</b>: {(f.get('reason') or '')[:120]}",
                        styles["Normal"],
                    )
                )
        else:
            story.append(Paragraph("No critical findings in the last 90 days.", styles["Normal"]))
        story.append(Spacer(1, 8))

        rem = summary.get("remediation_progress", {})
        story.append(
            Paragraph(
                f"<b>Remediation Progress:</b> {rem.get('percentage', 0)}%"
                f" ({rem.get('remediated', 0)}/{rem.get('total', 0)} resolved)",
                styles["Normal"],
            )
        )
        story.append(Spacer(1, 10))

        # FND-019: no published coverage percentage while EVF is Tier-3. Show the
        # frameworks in scope and their validation status, never a fabricated %.
        story.append(Paragraph("Framework Alignment — Validation Status", styles["Heading2"]))
        fc = summary.get("framework_coverage", {})
        if fc:
            fw_data = [["Framework", "EVF Validation Status"]] + [[k, str(v)] for k, v in fc.items()]
            fw_table = Table(fw_data, colWidths=[6 * cm, 9 * cm])
            fw_table.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e3a5f")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ("FONTSIZE", (0, 0), (-1, -1), 10),
                ("TOPPADDING", (0, 0), (-1, -1), 5),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ]))
            story.append(fw_table)
        story.append(Spacer(1, 12))

        story.append(HRFlowable(width="100%", thickness=0.5, color=colors.grey))
        story.append(Spacer(1, 4))
        disclaimer_style = ParagraphStyle(
            "disclaimer", parent=styles["Normal"], fontSize=8, textColor=colors.grey
        )
        story.append(Paragraph(_REPORT_DISCLAIMER, disclaimer_style))

        doc.build(story)
        buf.seek(0)
        return StreamingResponse(
            buf,
            media_type="application/pdf",
            headers={"Content-Disposition": "attachment; filename=saro-board-report.pdf"},
        )

    except ImportError:
        return summary


@router.get("/vendor-risk")
def get_vendor_risk_alias(
    db: Session = Depends(get_db),
    current_user=Depends(get_current_user),
    tenant_id: str | None = None,
):
    """Alias of /risk/vendors for React frontend compatibility."""
    return get_vendor_risk(db=db, current_user=current_user)
