"""
CF-01: TRACE Export - Signed PDF + Executive/Technical Toggle
=============================================================
POST /api/v1/trace/{audit_id}/export   - signed JSON export (HMAC-SHA256)
GET  /api/v1/trace/{audit_id}/export.pdf - streams signed PDF
POST /api/v1/trace/{audit_id}/verify   - tamper-detection verification
"""
from __future__ import annotations

import hashlib
import hmac
import json
import logging
import os
import uuid
from datetime import datetime, timezone
from typing import Annotated, Any

from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import Response
from sqlalchemy.orm import Session

from auth import get_current_user, require_role
from database import get_db
from models import Audit, AuditTrace, EnhancedTrace, ScanReport, User
from schemas import (
    ExecutiveStep,
    TraceExportOut,
    TraceVerifyIn,
    TraceVerifyOut,
)

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/api/v1/trace", tags=["trace-export"])

_HMAC_SECRET = os.environ.get("EXPORT_HMAC_SECRET", "saro-default-hmac-secret-change-in-prod")

_DISCLAIMER = (
    "This report is audit evidence generated by SARO v8.0.0. "
    "It does not constitute regulatory certification, legal advice, or compliance approval. "
    "Human review and sign-off by qualified personnel is required before any regulatory submission."
)

def _ascii(text: str) -> str:
    """Replace non-latin-1 characters with safe ASCII equivalents for core PDF fonts."""
    return (
        text.replace("—", "-").replace("–", "-")
        .replace("‘", "'").replace("’", "'")
        .replace("“", '"').replace("”", '"')
        .replace("•", "-")
        .encode("latin-1", errors="replace").decode("latin-1")
    )


_SEVERITY_MAP = {
    "fail": "Critical",
    "warn": "High",
    "flagged": "High",
    "triggered": "Medium",
    "pass": "Pass",
}


def _get_audit_or_404(audit_id: uuid.UUID, tenant_id: uuid.UUID, db: Session) -> Audit:
    audit = db.get(Audit, audit_id)
    if not audit or audit.tenant_id != tenant_id:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Audit not found")
    if audit.status != "completed":
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Audit is {audit.status} — export available only for completed audits.",
        )
    return audit


def _build_executive_steps(traces: list[AuditTrace]) -> list[ExecutiveStep]:
    """Generate plain-English executive steps from AuditTrace records (CF-01 AC-02)."""
    steps: list[ExecutiveStep] = []
    for t in traces:
        if t.result == "pass":
            continue
        label = t.gate_name
        severity = _SEVERITY_MAP.get(t.result, "Medium")

        if t.check_type == "compliance_rule":
            detail = t.detail_json or {}
            finding = (
                f"Compliance obligation triggered: {detail.get('title', t.check_name)}. "
                f"Framework: {detail.get('framework', 'N/A')}."
            )
        elif t.check_type == "risk_domain":
            finding = (
                f"Risk signals detected in domain '{t.check_name}'. "
                + (t.reason or "Review flagged samples.")
            )
        else:
            finding = t.reason or t.check_name

        # Truncate overly long findings for executive readability
        if len(finding) > 300:
            finding = finding[:297] + "..."

        steps.append(ExecutiveStep(label=label, finding=finding, severity=severity))
    return steps


def _sign_report(report_json: dict[str, Any]) -> str:
    """Compute HMAC-SHA256 over canonical JSON of report."""
    canonical = json.dumps(report_json, sort_keys=True, default=str)
    return hmac.new(
        _HMAC_SECRET.encode(),
        canonical.encode(),
        hashlib.sha256,
    ).hexdigest()


def _build_signed_json(
    audit: Audit,
    enhanced: EnhancedTrace,
    traces: list[AuditTrace],
    report: ScanReport,
) -> dict[str, Any]:
    exec_steps = _build_executive_steps(traces)
    report_json: dict[str, Any] = {
        "audit_id": str(audit.id),
        "dataset_name": audit.dataset_name,
        "completed_at": audit.completed_at.isoformat() if audit.completed_at else None,
        "executive_summary": enhanced.executive_summary,
        "executive_steps": [s.model_dump() for s in exec_steps],
        "confidence_score": report.confidence_score,
        "overall_risk_score": report.overall_risk_score,
        "mit_coverage_score": report.mit_coverage_score,
        "rule_pack_versions": _extract_rule_pack_versions(traces),
        "disclaimer": _DISCLAIMER,
    }
    export_hash = _sign_report(report_json)
    report_json["export_hash"] = export_hash
    return report_json, export_hash, exec_steps


def _extract_rule_pack_versions(traces: list[AuditTrace]) -> list[str]:
    seen: set[str] = set()
    versions: list[str] = []
    for t in traces:
        if t.check_type == "compliance_rule" and t.detail_json:
            rp = t.detail_json.get("rule_pack", {})
            ref = f"{rp.get('name', '')}@{rp.get('version', '')}" if rp else None
            if ref and ref not in seen:
                seen.add(ref)
                versions.append(ref)
    return versions


def _get_or_create_enhanced(
    audit: Audit, db: Session
) -> tuple[EnhancedTrace, list[AuditTrace]]:
    traces = (
        db.query(AuditTrace)
        .filter(AuditTrace.audit_id == audit.id)
        .order_by(AuditTrace.gate_id, AuditTrace.created_at)
        .all()
    )
    enhanced = db.query(EnhancedTrace).filter(EnhancedTrace.audit_id == audit.id).first()
    if not enhanced:
        # Synthesise a minimal enhanced trace if not yet generated
        enhanced = EnhancedTrace(
            audit_id=audit.id,
            chain_of_thought={},
            executive_summary=f"Audit {audit.id} completed.",
        )
        db.add(enhanced)
        db.flush()
    return enhanced, traces


@router.post(
    "/{audit_id}/export",
    response_model=TraceExportOut,
    dependencies=[Depends(require_role("super_admin", "operator"))],
    summary="CF-01: Export TRACE as signed JSON with HMAC-SHA256",
)
def export_trace(
    audit_id: uuid.UUID,
    current_user: Annotated[User, Depends(get_current_user)],
    db: Annotated[Session, Depends(get_db)],
) -> TraceExportOut:
    audit = _get_audit_or_404(audit_id, current_user.tenant_id, db)
    report = db.query(ScanReport).filter(ScanReport.audit_id == audit_id).first()
    if not report:
        raise HTTPException(status_code=404, detail="Audit report not found")

    enhanced, traces = _get_or_create_enhanced(audit, db)
    report_json, export_hash, exec_steps = _build_signed_json(audit, enhanced, traces, report)

    # Persist executive_steps and export_hash on EnhancedTrace
    enhanced.executive_steps = [s.model_dump() for s in exec_steps]
    enhanced.export_hash = export_hash
    db.commit()

    signed_at = datetime.now(tz=timezone.utc)
    return TraceExportOut(
        audit_id=audit_id,
        signed_json=report_json,
        export_hash=export_hash,
        signed_at=signed_at,
    )


@router.get(
    "/{audit_id}/export.pdf",
    dependencies=[Depends(require_role("super_admin", "operator"))],
    summary="CF-01: Stream signed PDF export of TRACE in Executive mode",
    responses={200: {"content": {"application/pdf": {}}}},
)
def export_trace_pdf(
    audit_id: uuid.UUID,
    current_user: Annotated[User, Depends(get_current_user)],
    db: Annotated[Session, Depends(get_db)],
) -> Response:
    audit = _get_audit_or_404(audit_id, current_user.tenant_id, db)
    report = db.query(ScanReport).filter(ScanReport.audit_id == audit_id).first()
    if not report:
        raise HTTPException(status_code=404, detail="Audit report not found")

    enhanced, traces = _get_or_create_enhanced(audit, db)
    report_json, export_hash, exec_steps = _build_signed_json(audit, enhanced, traces, report)

    # Persist if not already done
    if not enhanced.executive_steps:
        enhanced.executive_steps = [s.model_dump() for s in exec_steps]
    if not enhanced.export_hash:
        enhanced.export_hash = export_hash
    db.commit()

    pdf_bytes = _render_pdf(audit, exec_steps, report_json, export_hash)
    return Response(
        content=pdf_bytes,
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="saro-trace-{audit_id}.pdf"',
                 "X-Export-Hash": export_hash},
    )


@router.post(
    "/{audit_id}/verify",
    response_model=TraceVerifyOut,
    dependencies=[Depends(require_role("super_admin", "operator"))],
    summary="CF-01: Verify tamper-evident integrity of a TRACE export",
)
def verify_trace(
    audit_id: uuid.UUID,
    payload: TraceVerifyIn,
    current_user: Annotated[User, Depends(get_current_user)],
    db: Annotated[Session, Depends(get_db)],
) -> TraceVerifyOut:
    audit = _get_audit_or_404(audit_id, current_user.tenant_id, db)
    enhanced = db.query(EnhancedTrace).filter(EnhancedTrace.audit_id == audit_id).first()

    if not enhanced or not enhanced.export_hash:
        raise HTTPException(status_code=404, detail="No export found for this audit — run export first")

    if hmac.compare_digest(enhanced.export_hash, payload.export_hash):
        return TraceVerifyOut(valid=True)

    return TraceVerifyOut(valid=False, reason="hash_mismatch")


# ── PDF generation ──────────────────────────────────────────────────────────


def _render_pdf(
    audit: Audit,
    exec_steps: list[ExecutiveStep],
    report_json: dict[str, Any],
    export_hash: str,
) -> bytes:
    """Render executive trace report PDF using fpdf2 (pure Python, no system deps)."""
    from fpdf import FPDF, XPos, YPos

    now_str = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    rule_pack_refs = ", ".join(report_json.get("rule_pack_versions", [])) or "N/A"

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    pdf.set_left_margin(20)
    pdf.set_right_margin(20)
    pdf.set_top_margin(20)

    # Title
    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(26, 60, 94)
    pdf.cell(0, 10, "SARO Audit Evidence Report - Executive Mode",
             new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(1)
    pdf.set_draw_color(26, 60, 94)
    pdf.line(20, pdf.get_y(), 190, pdf.get_y())
    pdf.ln(4)

    # Metadata
    pdf.set_text_color(51, 51, 51)
    for label, value in [
        ("Audit ID", str(audit.id)),
        ("Dataset", _ascii(audit.dataset_name or "N/A")),
        ("Generated", now_str),
        ("Rule Packs", _ascii(rule_pack_refs)),
        ("Overall Risk Score", str(report_json.get("overall_risk_score", "N/A"))),
        ("Confidence", str(report_json.get("confidence_score", "N/A"))),
    ]:
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(45, 7, label + ":", new_x=XPos.RIGHT, new_y=YPos.TOP)
        pdf.set_font("Helvetica", "", 10)
        pdf.multi_cell(0, 7, value, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.ln(4)

    # Executive Summary
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(44, 95, 138)
    pdf.cell(0, 8, "Executive Summary", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(51, 51, 51)
    summary = _ascii(report_json.get("executive_summary", "No summary available."))
    pdf.multi_cell(0, 6, summary, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(4)

    # TRACE Timeline table
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(44, 95, 138)
    pdf.cell(0, 8, "TRACE Timeline - Executive Mode", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(2)

    # Table header
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_fill_color(26, 60, 94)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(55, 8, "Gate", border=1, fill=True, new_x=XPos.RIGHT, new_y=YPos.TOP)
    pdf.cell(100, 8, "Finding", border=1, fill=True, new_x=XPos.RIGHT, new_y=YPos.TOP)
    pdf.cell(25, 8, "Severity", border=1, fill=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    severity_colours = {
        "Critical": (192, 57, 43),
        "High": (230, 126, 34),
        "Medium": (243, 156, 18),
        "Low": (39, 174, 96),
        "Pass": (39, 174, 96),
    }
    pdf.set_font("Helvetica", "", 9)
    for step in exec_steps:
        r, g, b = severity_colours.get(step.severity, (85, 85, 85))
        pdf.set_text_color(51, 51, 51)
        finding_text = _ascii(step.finding)
        finding_short = finding_text[:120] + "..." if len(finding_text) > 120 else finding_text
        y_start = pdf.get_y()
        pdf.cell(55, 7, _ascii(step.label[:40]), border=1, new_x=XPos.RIGHT, new_y=YPos.TOP)
        pdf.multi_cell(100, 7, finding_short, border=1, new_x=XPos.RIGHT, new_y=YPos.TOP)
        y_end = pdf.get_y()
        row_h = max(7, y_end - y_start)
        pdf.set_xy(155, y_start)
        pdf.set_text_color(r, g, b)
        pdf.set_font("Helvetica", "B", 9)
        pdf.cell(25, row_h, step.severity, border=1, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.set_font("Helvetica", "", 9)

    # Disclaimer + hash
    pdf.ln(6)
    pdf.set_text_color(136, 136, 136)
    pdf.line(20, pdf.get_y(), 190, pdf.get_y())
    pdf.ln(2)
    pdf.set_font("Helvetica", "B", 8)
    pdf.cell(0, 5, "SHA-256 Integrity Hash:", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("Courier", "", 7)
    pdf.multi_cell(0, 4, export_hash, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(2)
    pdf.set_font("Helvetica", "I", 8)
    pdf.multi_cell(0, 5, _ascii(_DISCLAIMER), new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    return bytes(pdf.output())
